FROM ruby:2.3

RUN echo "deb http://ftp.us.debian.org/debian jessie-backports main" | tee -a /etc/apt/sources.list

RUN mkdir /client
RUN cd /client
WORKDIR /client

ADD Gemfile /client/Gemfile
ADD Gemfile.lock /client/Gemfile.lock
RUN gem install bundler
RUN bundle install

CMD bundle exec ruby paycheck_server.rb
